db = db.getSiblingDB("campuseats");

db.dishes.insertMany([
  {
    name: "Smash Burger Clasica",
    description: "Doble carne smash, cheddar fundido, cebolla caramelizada, salsa especial.",
    price: 8.5,
    category: "burgers",
    image: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Pizza Margherita",
    description: "Masa artesanal, tomate San Marzano, mozzarella fresca, albahaca.",
    price: 9.0,
    category: "pizza",
    image: "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 18,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Burrito Vegano",
    description: "Frijoles negros, arroz, guacamole, pico de gallo, salsa chipotle.",
    price: 7.5,
    category: "mexicano",
    image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Ramen Tonkotsu",
    description: "Caldo de cerdo 12h, noodles frescos, huevo marinado, chashu, nori.",
    price: 11.0,
    category: "asiatico",
    image: "https://images.pexels.com/photos/884600/pexels-photo-884600.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Tortilla de Patatas",
    description: "Receta de la abuela. Patata, cebolla, huevo. Jugosa por dentro.",
    price: 5.5,
    category: "espanol",
    image: "https://images.pexels.com/photos/6605961/pexels-photo-6605961.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Poke Bowl Salmon",
    description: "Salmon fresco, arroz de sushi, edamame, aguacate, mango, salsa ponzu.",
    price: 10.5,
    category: "asiatico",
    image: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Churros con Chocolate",
    description: "Churros recien hechos con chocolate caliente a la taza.",
    price: 4.5,
    category: "postres",
    image: "https://images.pexels.com/photos/2116094/pexels-photo-2116094.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "Tacos al Pastor",
    description: "Tres tacos de cerdo marinado, pina asada, cilantro, cebolla, salsa verde.",
    price: 8.0,
    category: "mexicano",
    image: "https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&w=500",
    available: true,
    prepTime: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

print("CampusEats: 8 platos insertados");
