apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfitness-frontend
  labels:
    app: myfitness-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfitness-frontend
  template:
    metadata:
      labels:
        app: myfitness-frontend
    spec:
      containers:
        - name: myfitness-frontend
          image: myfitness-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
